##########################
### MACRO: Uranium 238 ###
##########################

# Distance units: [mm]  

/source/isIon 1
/source/Z 92
/source/A 238

# Cube dimensions
/cube/Cube_Width 10
/cube/Cube_Length 10
/cube/Cube_Height 10

# Fiducial Cube dimensions
/cube/FiducialCube_Width 8
/cube/FiducialCube_Length 8
/cube/FiducialCube_Height 8

# Cube position
/cube/xCube 40
/cube/yCube 0
/cube/zCube 5

# Lithium relative abundances
/cube/Li7_percent 93
/cube/Li6_percent 7

/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+30 year